services:  
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    container_name: culturadb
    volumes:
      - ./postgres:/var/lib/postgresql/data
